services:
  - type: web
    name: minecraft-blacklist-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: API_KEY
        value: "204r8382394"
      - key: NODE_ENV
        value: "production"
